# Generated by Django 2.1 on 2020-02-20 11:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 11, 5, 34, 977611, tzinfo=utc)),
        ),
    ]
